import csv
import unittest

from path.root_path import root_path


class MyTestCase(unittest.TestCase):
    def test_something(self):
        with open(root_path + "/siren/siren.csv", "r", encoding="utf8") as sirene:
            reader = csv.DictReader(sirene)
            for row in reader:
                print("siren", row["siren"])
                print("nic", row["nic"])
                print("siret", row["siret"])
                print("statutDiffusionEtablissement", row["statutDiffusionEtablissement"])
                print("dateCreationEtablissement", row["dateCreationEtablissement"])
                print("trancheEffectifsEtablissement", row["trancheEffectifsEtablissement"])
                print("anneeEffectifsEtablissement", row["anneeEffectifsEtablissement"])
                print("activitePrincipaleRegistreMetiersEtablissement", row["activitePrincipaleRegistreMetiersEtablissement"])
                print("dateDernierTraitementEtablissement", row["dateDernierTraitementEtablissement"])
                print("etablissementSiege -----", row["etablissementSiege"])
                print("etatAdministratifUniteLegale", row["etatAdministratifUniteLegale"])
                print("statutDiffusionUniteLegale", row["statutDiffusionUniteLegale"])
                print("unitePurgeeUniteLegale", row["unitePurgeeUniteLegale"])
                print("dateCreationUniteLegale", row["dateCreationUniteLegale"])
                print("categorieJuridiqueUniteLegale", row["categorieJuridiqueUniteLegale"])
                print("denominationUniteLegale", row["denominationUniteLegale"])
                print("sigleUniteLegale", row["sigleUniteLegale"])
                print("denominationUsuelle1UniteLegale", row["denominationUsuelle1UniteLegale"])
                print("denominationUsuelle2UniteLegale", row["denominationUsuelle2UniteLegale"])
                print("denominationUsuelle3UniteLegale", row["denominationUsuelle3UniteLegale"])
                print("sexeUniteLegale", row["sexeUniteLegale"])
                print("nomUniteLegale", row["nomUniteLegale"])
                print("nomUsageUniteLegale", row["nomUsageUniteLegale"])
                print("prenom1UniteLegale", row["prenom1UniteLegale"])
                print("prenom2UniteLegale", row["prenom2UniteLegale"])
                print("prenom3UniteLegale", row["prenom3UniteLegale"])
                print("prenom4UniteLegale", row["prenom4UniteLegale"])
                print("prenomUsuelUniteLegale", row["prenomUsuelUniteLegale"])
                print("pseudonymeUniteLegale", row["pseudonymeUniteLegale"])
                print("activitePrincipaleUniteLegale -----", row["activitePrincipaleUniteLegale"])
                print("nomenclatureActivitePrincipaleUniteLegale", row["nomenclatureActivitePrincipaleUniteLegale"])
                print("identifiantAssociationUniteLegale", row["identifiantAssociationUniteLegale"])
                print("economieSocialeSolidaireUniteLegale", row["economieSocialeSolidaireUniteLegale"])
                print("societeMissionUniteLegale", row["societeMissionUniteLegale"])
                print("caractereEmployeurUniteLegale", row["caractereEmployeurUniteLegale"])
                print("trancheEffectifsUniteLegale", row["trancheEffectifsUniteLegale"])
                print("anneeEffectifsUniteLegale", row["anneeEffectifsUniteLegale"])
                print("nicSiegeUniteLegale", row["nicSiegeUniteLegale"])
                print("dateDernierTraitementUniteLegale", row["dateDernierTraitementUniteLegale"])
                print("categorieEntreprise", row["categorieEntreprise"])
                print("anneeCategorieEntreprise", row["anneeCategorieEntreprise"])
                print("complementAdresseEtablissement", row["complementAdresseEtablissement"])
                print("numeroVoieEtablissement", row["numeroVoieEtablissement"])
                print("indiceRepetitionEtablissement", row["indiceRepetitionEtablissement"])
                print("typeVoieEtablissement", row["typeVoieEtablissement"])
                print("libelleVoieEtablissement", row["libelleVoieEtablissement"])
                print("codePostalEtablissement", row["codePostalEtablissement"])
                print("libelleCommuneEtablissement", row["libelleCommuneEtablissement"])
                print("libelleCommuneEtrangerEtablissement", row["libelleCommuneEtrangerEtablissement"])
                print("distributionSpecialeEtablissement", row["distributionSpecialeEtablissement"])
                print("codeCommuneEtablissement", row["codeCommuneEtablissement"])
                print("codeCedexEtablissement", row["codeCedexEtablissement"])
                print("libelleCedexEtablissement", row["libelleCedexEtablissement"])
                print("codePaysEtrangerEtablissement", row["codePaysEtrangerEtablissement"])
                print("libellePaysEtrangerEtablissement", row["libellePaysEtrangerEtablissement"])
                print("complementAdresse2Etablissement", row["complementAdresse2Etablissement"])
                print("numeroVoie2Etablissement", row["numeroVoie2Etablissement"])
                print("indiceRepetition2Etablissement", row["indiceRepetition2Etablissement"])
                print("typeVoie2Etablissement", row["typeVoie2Etablissement"])
                print("libelleVoie2Etablissement", row["libelleVoie2Etablissement"])
                print("codePostal2Etablissement", row["codePostal2Etablissement"])
                print("libelleCommune2Etablissement", row["libelleCommune2Etablissement"])
                print("libelleCommuneEtranger2Etablissement", row["libelleCommuneEtranger2Etablissement"])
                print("distributionSpeciale2Etablissement", row["distributionSpeciale2Etablissement"])
                print("codeCommune2Etablissement", row["codeCommune2Etablissement"])
                print("codeCedex2Etablissement", row["codeCedex2Etablissement"])
                print("libelleCedex2Etablissement", row["libelleCedex2Etablissement"])
                print("codePaysEtranger2Etablissement", row["codePaysEtranger2Etablissement"])
                print("libellePaysEtranger2Etablissement", row["libellePaysEtranger2Etablissement"])
                print("etatAdministratifEtablissement", row["etatAdministratifEtablissement"])
                print("enseigne1Etablissement", row["enseigne1Etablissement"])
                print("enseigne2Etablissement", row["enseigne2Etablissement"])
                print("enseigne3Etablissement", row["enseigne3Etablissement"])
                print("denominationUsuelleEtablissement", row["denominationUsuelleEtablissement"])
                print("activitePrincipaleEtablissement", row["activitePrincipaleEtablissement"])
                print("nomenclatureActivitePrincipaleEtablissement", row["nomenclatureActivitePrincipaleEtablissement"])
                print("caractereEmployeurEtablissement", row["caractereEmployeurEtablissement"])
                break
